import './globals.css'
import { Lora } from 'next/font/google'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'

const lora = Lora({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header />
      <body className={lora.className}>{children}</body>
      <Footer />
    </html>
  )
}
